# -*- coding: utf-8 -*-
"""charis_salesPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AG5ygn-1aZt1ODWnNFFW5sBm_v8PQZ04
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile salesSVM.py
# import streamlit as st
# import pandas as pd
# import pickle
# 
# st.write("""
# # Sales Prediction App
# 
# This app predicts the **Sales**!
# """)
# 
# st.sidebar.header('User Input Parameters')
# 
# def user_input_features():
#     TV = st.sidebar.slider('TV', 4.3, 7.9, 5.4)
#     radio = st.sidebar.slider('Radio', 2.0, 4.4, 3.4)
#     newspaper = st.sidebar.slider('Newspaper', 1.0, 6.9, 1.3)
# 
#     data = {'TV': TV,
#             'radio': radio,
#             'newspaper': newspaper
#           }
#     features = pd.DataFrame(data, index=[0])
#     return features
# 
# df = user_input_features()
# 
# st.subheader('User Input parameters')
# st.write(df)
# 
# loaded_model = pickle.load(open("modelcharis.h5", "rb"))
# 
# prediction = loaded_model.predict(df)
# 
# st.subheader('Prediction')
# st.write(prediction)
#
